homeassistant:
  name: Jarvis Home
  time_zone: America/Chicago
  # valid values: 'metric' or 'imperial' ('imperial' matches US customary)
  unit_system: imperial
  currency: USD

default_config:
# Example configuration.yaml entry
assist_pipeline:

automation: !include_dir_merge_list automations
